### ISSUE TITLE
关于“global.h”头文件

### ISSUE THREAD

**Issue by buzoubuzou** [jt-chairman/yolov7-seg-onnx#1]
作者你好，我借鉴了你的代码，发现没有包含global.h的文件。

**Comment by jt-chairman** [comment]
不好意思，是从大项目单独拉出来的代码，稍后我补上。

**Comment by jt-chairman** [comment]
> 作者你好，我借鉴了你的代码，发现没有包含global.h的文件。

修改了依赖关系，应该可以运行了，有任何问题可以讨论，谢谢

**Comment by buzoubuzou** [comment]
非常感谢!
