### ISSUE TITLE
关于“yolov7.cpp”中"Mat masks_2d"报错

### ISSUE THREAD

**Issue by buzoubuzou** [jt-chairman/yolov7-seg-onnx#2]
作者你好！更新后的cpp文件241，248，255行代码的Mat未做修改。我按照你的格式改成CV_8U形式还是会出现报错。能不能帮忙解决一下！

**Comment by jt-chairman** [comment]
> 作者你好！更新后的cpp文件241，248，255行代码的Mat未做修改。我按照你的格式改成CV_8U形式还是会出现报错。能不能帮忙解决一下！

您的onnx输出格式是8位整型吗？您可以贴上错误信息和您的onnx模型输出供参考。如果输出类型是float，建议不要更改变量类型。

**Comment by buzoubuzou** [comment]
您好！我这边onnx模型输出是float32。
然后报错是一个opencv错误：terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1) /home/westwell/code/c_/opencv-4.5.1/modules/core/src/matmul.dispatch.cpp:344: error: (-215:Assertion failed) a_size.width == len in function 'gemm'。
报错位置是：Mat masks_2d = masks_in_m * proto_2d;
麻烦您帮我看一下，十分感谢！

**Comment by buzoubuzou** [comment]
这两个输出维度不一样导致的这个错误吧？

**Comment by jt-chairman** [comment]
> 您好！我这边onnx模型输出是float32。
> 
> 然后报错是一个opencv错误：terminate called after throwing an instance of 'cv::Exception'
> 
>   what():  OpenCV(4.5.1) /home/westwell/code/c_/opencv-4.5.1/modules/core/src/matmul.dispatch.cpp:344: error: (-215:Assertion failed) a_size.width == len in function 'gemm'。
> 
> 报错位置是：Mat masks_2d = masks_in_m * proto_2d;
> 
> 麻烦您帮我看一下，十分感谢！

问题出在两个矩阵相乘维度不匹配，您可以在错误处查看两个矩阵的维度。因为这个代码是针对本人的onnx模型写的，所以代码可能没有普适其他onnx模型，请将netron.app模型输出截图做参考，谢谢。

**Comment by buzoubuzou** [comment]
![20230103-215300](https://user-images.githubusercontent.com/52873038/210370828-f92cf90a-b9e2-49c4-9d9d-47e99bb633af.jpg)

**Comment by jt-chairman** [comment]
> 这两个输出维度不一样导致的这个错误吧？

实际上，这两个矩阵并不是onnx模型的直接输出，其中的计算方法与yolo的输出网络设计有关。

**Comment by jt-chairman** [comment]
> 
> 
> ![20230103-215300](https://user-images.githubusercontent.com/52873038/210370828-f92cf90a-b9e2-49c4-9d9d-47e99bb633af.jpg)
> 
> 
> 
> 
> 
> 
> 
> 

另请提供您错误处的两个矩阵维度

**Comment by buzoubuzou** [comment]
mask_in_m[38 x 3]
proto_2d[17920 x 32]

**Comment by jt-chairman** [comment]
> mask_in_m[38 x 3]
> 
> proto_2d[17920 x 32]

您是否修改了362-366行代码？onnx模型输出的结果中，并不是所有都有用(我改写原作者后处理代码发现)。只需要处理其中的两个，一个应该是您onnx模型的output，其中包含置信度、bbox等信息。另一个则是mask，具体对应您onnx模型输出中的第几个，我需要回顾一下代码才能回复您。

**Comment by buzoubuzou** [comment]
您好，362-366行代码我没有做改动，我的输出也是output和mask第五个输出513。这个我和你对原作者代码理解是一致的。

**Comment by buzoubuzou** [comment]
可否上传一个链接共享您的onnx模型，然后我可以依照你的模型理解你的思路，去适配修改我的代码。

**Comment by jt-chairman** [comment]
> 可否上传一个链接共享您的onnx模型，然后我可以依照你的模型理解你的思路，去适配修改我的代码。

sorry，我的onnx是大文件无法上传。我查看一下矩阵的运算流程，稍后给您一些反馈。

**Comment by buzoubuzou** [comment]
好的，麻烦你了。顺便问一下，您这边推理时间是多少（GPU/CPU）？

**Comment by jt-chairman** [comment]
> 好的，麻烦你了。顺便问一下，您这边推理时间是多少（GPU/CPU）？

我这边cpu推理1.5s一张，图片大小是1024*704

**Comment by jt-chairman** [comment]
> mask_in_m[38 x 3] proto_2d[17920 x 32]

问题似乎出现在mask_in_m中的38维，理应是32。3维代表onnx模型目标检测极大值抑制后检测到的目标数量。方便提供您的onnx模型以及一张图片给我，我看看问题所在吗？

**Comment by buzoubuzou** [comment]
百度网盘，麻烦下载一下
链接：https://pan.baidu.com/s/1ZU65fYvsq4WJfgn93kc1rw 
提取码：4m4j

**Comment by buzoubuzou** [comment]
我做了一个尝试：我把cpp文件里面229行代码的 ii = 6改成ii=12，得到了相同维度然后得到了正确的结果。

**Comment by jt-chairman** [comment]
> 我做了一个尝试：我把cpp文件里面229行代码的 ii = 6改成ii=12，得到了相同维度然后得到了正确的结果。

非常聪明，确实应该是这里的问题，您的分类数量是8类吗？请查看输出的rect图片是否正确？

**Comment by buzoubuzou** [comment]
是8类，能解释一下12的原理吗？非常感谢。输出是一张整体的目标检测和分别每个实例的mask图片

**Comment by jt-chairman** [comment]
刚刚查了一下原因，根本原因是line #137中pred输出我限定了从第7列开始输出。由于我个人的分类数目只有2类，因此yolov7output中各列的含义是这样的：

- 0 : 3 bbox
- 4 obj_conf
- 5 : 5 + #classes(2 in this case) cls_conf
- else mask
您的onnx模型各列的含义为：
- 0 : 3 bbox
- 4 obj_conf
- 5 : 5 + #classes(8 in this case) cls_conf
- else mask
因此使用您的onnx模型，函数nonMaxSuppression返回结果中7：11行是多余的。

我马上会将修改好的代码commit，您可以使用修改后的代码，或者将line #137修改为
			for (int ii = mi; ii < shape[2]; ii++) {

**Comment by jt-chairman** [comment]
> 是8类，能解释一下12的原理吗？非常感谢。输出是一张整体的目标检测和分别每个实例的mask图片

刚刚查了一下原因，根本原因是line #137中pred输出我限定了从第7列开始输出。由于我个人的分类数目只有2类，因此yolov7output中各列的含义是这样的：

- 0 : 3 bbox
- 4 obj_conf
- 5 : 5 + #classes(2 in this case) cls_conf
- else mask

您的onnx模型各列的含义为：
- 0 : 3 bbox
- 4 obj_conf
- 5 : 5 + #classes(8 in this case) cls_conf
- else mask
因此使用您的onnx模型，函数nonMaxSuppression返回结果中7：11行是多余的。

我马上会将修改好的代码commit，您可以使用修改后的代码，或者将line #137修改为
			for (int ii = mi; ii < shape[2]; ii++) {

**Comment by buzoubuzou** [comment]
好的，非常感谢能开源yolov7-seg的c++版本代码！
